### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-carlos-chrs#1]
[infografia_realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-carlos-chrs/files/10769771/infografia_realidad.aumentada.pdf)

**Comment by IsraelNicolas61** [comment]
18% de 20%

Falta un poco de creatividad e info

**Comment by IsraelNicolas61** [comment]
20% buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
